# Generated by Django 4.1.1 on 2022-10-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
